// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/work_notifier.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/work_notifier.go -destination=internal/usecase/mock/mock_work_notifier.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkNotifier is a mock of WorkNotifier interface.
type MockWorkNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockWorkNotifierMockRecorder
	isgomock struct{}
}

// MockWorkNotifierMockRecorder is the mock recorder for MockWorkNotifier.
type MockWorkNotifierMockRecorder struct {
	mock *MockWorkNotifier
}

// NewMockWorkNotifier creates a new mock instance.
func NewMockWorkNotifier(ctrl *gomock.Controller) *MockWorkNotifier {
	mock := &MockWorkNotifier{ctrl: ctrl}
	mock.recorder = &MockWorkNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkNotifier) EXPECT() *MockWorkNotifierMockRecorder {
	return m.recorder
}

// NotifyCreated mocks base method.
func (m *MockWorkNotifier) NotifyCreated(ctx context.Context, work *entity.Work) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyCreated", ctx, work)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyCreated indicates an expected call of NotifyCreated.
func (mr *MockWorkNotifierMockRecorder) NotifyCreated(ctx, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyCreated", reflect.TypeOf((*MockWorkNotifier)(nil).NotifyCreated), ctx, work)
}
