// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/webhook_notifier.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/webhook_notifier.go -destination=internal/usecase/mock/mock_webhook_notifier_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookNotifierRepository is a mock of WebhookNotifierRepository interface.
type MockWebhookNotifierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookNotifierRepositoryMockRecorder
	isgomock struct{}
}

// MockWebhookNotifierRepositoryMockRecorder is the mock recorder for MockWebhookNotifierRepository.
type MockWebhookNotifierRepositoryMockRecorder struct {
	mock *MockWebhookNotifierRepository
}

// NewMockWebhookNotifierRepository creates a new mock instance.
func NewMockWebhookNotifierRepository(ctrl *gomock.Controller) *MockWebhookNotifierRepository {
	mock := &MockWebhookNotifierRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookNotifierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookNotifierRepository) EXPECT() *MockWebhookNotifierRepositoryMockRecorder {
	return m.recorder
}

// WebhookNotify mocks base method.
func (m *MockWebhookNotifierRepository) WebhookNotify(ctx context.Context, work *entity.Work) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebhookNotify", ctx, work)
	ret0, _ := ret[0].(error)
	return ret0
}

// WebhookNotify indicates an expected call of WebhookNotify.
func (mr *MockWebhookNotifierRepositoryMockRecorder) WebhookNotify(ctx, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebhookNotify", reflect.TypeOf((*MockWebhookNotifierRepository)(nil).WebhookNotify), ctx, work)
}
